version: '3.7'

services:
  app:
    image: "${SERVICE_NAME}-${ENV}-${ORGANIZATION}:latest"
    container_name: "${SERVICE_NAME}.${ENV}.${ORGANIZATION}-${SERVER}.internal"
    build:
      context: .
      args:
        BL_NPM_REGISTRY_TOKEN: "${BL_NPM_REGISTRY_TOKEN}"
    env_file:
      - ./.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    restart: unless-stopped
    ports: 
      - "${PORT}:${PORT}"
    volumes:
      - ./database:/app/database
    command: "${COMMAND}"
